# Base image
FROM python:3.10
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements_celery.txt /app

# Diğer gerekli bağımlılıkları yükleyin
RUN pip install -r requirements_celery.txt

# Servis dosyalarını Docker içine kopyalayın
COPY algorithm.py /app/algorithm.py

# Çalıştırılacak komutu belirtin
CMD ["celery", "-A", "algorithm.myCelery", "worker", "--loglevel=info"]
